name: Validate PRs
on:
  pull_request:
    paths:
      - 'docker/Dockerfile'
      - '.github/workflows/build-installer-kernel-builder-image.yml'
      - '.github/workflows/validate-pr.yml'

jobs:
  validate-build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Build image (no push)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: docker/Dockerfile
          push: false
